name: My first CI Pipeline
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checckout@v4

      - name: Say hello
        run: echo "My first Github Actions workflow works!"
      
