name: My first CI Pipeline

on:
 push:
 pull_request:

jobs:
  test:
     runs-on: ubuntu-latest

     steps:
       - name: Check out code
         uses: actions/checkout@v4

       - name: Set up Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.12'
       - name: Install dependencies
         run: pip install -r api/requirements.txt
       - name: Run password tests
         run: python api/test.py
       - name: Run hash test
         run: python "api/test_hash.py"
       - name: Run password tests 2
         run: python "api/test_password.py"
       - name: Build Docker image
         run: docker build -t three-tier-api ./api
       - name: Run Docker container
         run: docker run -d -p 8000:8000 --name three-tier-api three-tier-api
       - name: Say hello
         run: echo "My first Github actions workflow works!"
