name: My first CI Pipeline

on:
 push:
 pull_request:

 permissions:
   id-token: write
   contents: read 

jobs:
  test:
     runs-on: ubuntu-latest

     steps:
       - name: Check out code
         uses: actions/checkout@v4
      
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         role-to-assume: arn:aws:iam::298712671997:role/githubaction-ecr-deploy
           aws-region: us-east-1

       - name: Set up Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.12'
       - name: Install dependencies
         run: pip install -r api/requirements.txt
       - name: Run password tests
         run: python api/test.py
       - name: Run hash test
         run: python "api/test_hash.py"
       - name: Run password tests 2
         run: python "api/test_password.py"
       - name: Build Docker image
         run: docker build -t three-tier-api ./api
       - name: Run Docker container
         run: docker run -d -p 8000:8000 --name three-tier-api three-tier-api
       - name: test fastapi import
         run: |
           docker exec three-tier-api python -c "from main import app; print(app)"
       - name: check uvicorn command
         run: | 
           docker exec three-tier-api ps aux
           docker exec three-tier-api cat /proc/1/cmdline | tr '\0' ' ' 
           echo
       - name: check running processes
         run: docker exec three-tier-api ps aux
       - name: Check listening ports
         run: docker exec three-tier-api python -c "import socket; s=socket.socket(); print('port 8000:', 'OPEN' if s.connect_ex(('127.0.0.1' ,8000)) == 0 else 'CLOSED')"
       - name: check container status
         run: docker ps -a
       - name: CHECK CONTAINER LOGS
         run: docker logs three-tier-api
       - name: check port 8000 inside container
         run: |
           docker exec three-tier-api python -c "import socket; s=socket.socket(); print('PORT 8000:', 'OPEN' if s.connect_ex(('127.0.0.1',8000)) == 0 else 'CLOSED')"
       - name: Test API inside container
         run: docker exec three-tier-api python -c "import socket; s=socket.socket(); print('PORT 8000:', 'OPEN' if s.connect_ex(('127.0.0.1',8000)) == 0 else 'CLOSED')"
       - name: Test API
         run: |
            sleep 5
            curl --fail http://localhost:8000
       - name: Build Nginx docker image
         run: docker build -t nginx-test .
       - name: Validate databse compose
         run: docker compose -f database/docker-compose.yml config
       - name: start database
         run: docker compose -f database/docker-compose.yml up -d
       - name: check database
         run: docker compose -f database/docker-compose.yml ps
       - name: stop database
         if: always()
         run: docker compose -f database/docker-compose.yml down
       - name: Say hello
         run: echo "My first Github actions workflow works!"
